### ISSUE TITLE
create conffiles for odn-box

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/odn-box#1]
Otherwise the installation will remove old conf files without asking.

to finish https://github.com/OpenDataNode/odn-box/commit/ce1fca642b2c7137b224869fa67b7c70b0c302ee

**Comment by Jan-Marcek** [comment]
fixed by https://github.com/OpenDataNode/odn-box/commit/b7a646ac5bd6f8bd71f44962d1b8b8de62ace758

**Comment by skrchnavy** [comment]
not fixed

**Comment by Jan-Marcek** [comment]
fixed - out of box.
http://www.tin.org/bin/man.cgi?section=1&topic=dh_installdeb

```
 In v3 compatibility mode and higher, all files in the etc/
           directory in a package will automatically be flagged as conffiles
           by this program, so there is no need to list them manually here.
```
