### ISSUE TITLE
prompt user for hostname when odn-box is installing.

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/odn-box#10]

**Comment by skrchnavy** [comment]
@Jan-Marcek is this valid? Better description is missing

**Comment by Jan-Marcek** [comment]
Do we want this?

**Comment by skrchnavy** [comment]
@hanecak @peterklimo - is this required? Is clear what shall be done?

**Comment by peterklimo** [comment]
I do not see any use case for that

**Comment by Jan-Marcek** [comment]
@mkl-eea-sk mentioned that he has a case where prompt can be useful. Please provide your idea.

**Comment by ghost** [comment]
@peterklimo when i do not want to change my hostname but i want to access ODN under some other name (other than my hostname)... when i install on my host, for example, i feel comfortable using my IP or "localhost" but i simply cannot do this.

**Comment by skrchnavy** [comment]
The idea shall be that all components are accessible via localhost and there is reverse proxy server that is able to handle all names (hosts) that are assigned to the server. Also IP addresses shall be then properly served.

**Comment by skrchnavy** [comment]
@peterklimo - are all components ready to work behind proxy?

**Comment by peterklimo** [comment]
yes
