### ISSUE TITLE
Add virtuoso debian package dependency

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/odn-box#2]
virtuoso is not shipping in odn-box, dependency must be added to install it.

**Comment by skrchnavy** [comment]
To select which version of virtuoso debian package to use (from LOD2 stack or another?)

**Comment by ghost** [comment]
beware, virtuoso is optional (suggests or recommended) not depends
dependency

**Comment by skrchnavy** [comment]
Virtuoso is mandatory component in ODN as SPARQL endpoint (based on proposed design)

**Comment by Jan-Marcek** [comment]
fixed
