### ISSUE TITLE
Log level of midpoint shall not be TRACE

### ISSUE THREAD

**Issue by skrchnavy** [OpenDataNode/odn-box#20]
Based on OpenDataNode/open-data-node#122 - Logging from midpoint is excessive. Log level is by default set to trace. It shall be higher to reduce logging.

TCID: ODN-370

**Comment by Jan-Marcek** [comment]
it was fixed by https://github.com/OpenDataNode/odn-box/blob/develop/midpoint/conf/web.xml#L92
It was caused by the fact that we were using snapshot version of midpoint.

https://github.com/OpenDataNode/open-data-node/issues/122#issuecomment-103861986

**Comment by Jan-Marcek** [comment]
fixed again by https://github.com/OpenDataNode/odn-box/commit/916b60121eaa23e1a6925e2663bad90a5b5afcc1
