### ISSUE TITLE
Adding certificate to apache /etc/ssl/certs/ should be done at odn-cas

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/odn-box#23]
Motivation:
odn-cas is responsible for creation certificate for host. It puts a generated certificate to `/usr/local/share/ca-certificates/` and `/usr/share/odn-cas/conf/.keystore` at [odn-cas:generate_keystore()](https://github.com/OpenDataNode/odn-cas/blob/master/src/deb/control/postinst#L61). odn-cas should place the cerificate to `/etc/ssl/certs/` as well.  ( /etc/ssl/certs/ is important for apache2 because it reads certs from here). This function [apache_ssl() at odn-cas](https://github.com/OpenDataNode/odn-box/blob/master/debian/odn-simple.postinst#L150) is hot fix - It takes cert from `/usr/share/odn-cas/conf/.keystore` and put to `/etc/ssl/certs/`. 

odn-cas shall propagate generated certificate to the all important places.

**Comment by skrchnavy** [comment]
Moved to proper component (odn cas) as issue OpenDataNode/odn-cas#2
