### ISSUE TITLE
unable create pipeline via ckan when user haven't logged to uv

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/odn-box#25]
If a user has never logged to unifiedviews then he is unable create pipeline via ckan

**Comment by skrchnavy** [comment]
related to user provisioning, shall be reported to https://github.com/OpenDataNode/open-data-node/issues

**Comment by Jan-Marcek** [comment]
moved https://github.com/OpenDataNode/open-data-node/issues/127

**Comment by skrchnavy** [comment]
closed not relevant for this component
