### ISSUE TITLE
Installation of CKAN theme in ODN-Box

### ISSUE THREAD

**Issue by skrchnavy** [OpenDataNode/odn-box#27]
Currently, theme is installed in ODN--CKAN (see https://github.com/OpenDataNode/odn-ckan/blob/24335db4c1aa9dcce6e55da821f8e5fc371d03a0/requirements.txt where is

```
git+https://github.com/OpenDataNode/ckanext-odn-theme.git@ODN_v1.0.2#egg=ckanext-odn-theme
```

and this theme is enabled (configured to be loaded) in odn-box for IC in  file https://github.com/OpenDataNode/odn-box/blob/ODN_v1.0.2/ckan-ic/production.ini and for PC https://github.com/OpenDataNode/odn-box/blob/ODN_v1.0.2/ckan-Pc/production.ini as plugi: odn_theme

```
ckan.plugins = stats text_preview recline_preview datastore odn_pipeline odn_theme odn_ic2pc_sync odn_resource_update_api odn_package_extras odn_cas audited_datastore internal_api
```

The background of requirement is to be able to install/replace any theme.

(there is partially related idea for CKAN: https://github.com/ckan/ideas-and-roadmap/issues/74 )

**Comment by Jan-Marcek** [comment]
fixed by https://github.com/OpenDataNode/odn-ckan/commit/d18cf8632ceb3ce8cd7b32f6cefc455bbfe2059c

Now, when odn-box is about to build ckanext-odn-theme is copied into ckan-commns. This is done by Jenkins job.
