### ISSUE TITLE
to create query for virtuoso sparql endpoint editor

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/odn-box#29]
Ckan creates rdf resource for dataset. Rdf resource is represented by URL. This url is generated from a template. The template is configured in https://github.com/OpenDataNode/odn-box/blob/master/ckan-ic/production.ini#L143. We have to define some sparql query template (because of solution https://github.com/OpenDataNode/odn-box/issues/6). Our suggested query is `select * where {?a ?b ?c}`

Please confirm or provide a suitable query for Virtuoso sparql endpoint editor. 

![sparql_editor_query](https://cloud.githubusercontent.com/assets/5822680/8002267/9ce40d4e-0b6d-11e5-9186-b95d1264efe8.png)

**Comment by tomas-knap** [comment]
Dejme select \* where {?s ?p ?o} LIMIT 1000, tedy s tim limitem

**Comment by Jan-Marcek** [comment]
adjusted

**Comment by Jan-Marcek** [comment]
I changed my mind: this looks better. `select * where {?s ?p ?o} LIMIT 1000`

**Comment by skrchnavy** [comment]
why not `SELECT * WHERE {?s ?p ?o} LIMIT 1000` or `select * where {?s ?p ?o} limit 1000` ?
