### ISSUE TITLE
error regarding uv-l-catalog observerd during installation

### ISSUE THREAD

**Issue by hanecak** [OpenDataNode/odn-box#31]
While installing ODN (following steps in https://utopia.sk/wiki/display/ODN/Open+Data+Node+v1.0.2) I encountered following error on the console:

```
...
..installing /usr/share/unifiedviews/dist/plugins/uv-t-zipper-2.0.1.jar: OK
---------------------------------------------------------------------
Installing DPUs..
..target instance: http://127.0.0.1:28080/master/api/1/import/dpu/jar
---------------------------------------------------------------------
ls: cannot access /usr/share/unifiedviews/dist/odn_plugins/uv-l-catalog-*.jar: No such file or directory
..installing : OK
..installing /usr/share/unifiedviews/dist/odn_plugins/uv-l-filesToCkan-1.0.2.jar: OK
...
```

I was installing ODN using command `aptitude install --without-recommends odn-simple`.

After that step, all seems OK, installation completed and I'm able to log into ODN. So this is a low priority issue.

**Comment by Jan-Marcek** [comment]
fixed by https://github.com/OpenDataNode/ODN-UV-Plugins/commit/ce7313aee698878b622c2fbfe0b8b1907df1040e

There was obsolete dpu.
