### ISSUE TITLE
dumps are not accessible from host

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/odn-box#32]
A user wants to publish the dump.zip.
The dump.zip is placed into `/var/www/dump/` by using DPU uv-l-filesUpload. The folder is shared by apache2 [odn-simple-apache.conf#L9](https://github.com/OpenDataNode/odn-box/blob/master/apache/odn-simple-apache.conf#L9)  and [odn-simple-apache.conf#L48](https://github.com/OpenDataNode/odn-box/blob/master/apache/odn-simple-apache.conf#L48)

But after the commit https://github.com/OpenDataNode/odn-box/commit/9cf5b556556282e026a0cc679e7292321dfd28a2 /dump is no longer accessible.

**Comment by Jan-Marcek** [comment]
@skrchnavy should be dumps reachable via http or https? or both?

**Comment by skrchnavy** [comment]
I think both because user shall see data using scheme (s)he enters catalog.

**Comment by Jan-Marcek** [comment]
I realized that https://github.com/OpenDataNode/odn-box/blob/develop/ckan-ic/production.ini#L144 is used by L-catalog. As far as I know we don't distribute L-catalog - https://github.com/OpenDataNode/odn-box/issues/31. @skrchnavy  Are we going to support L-catalog ?

**Comment by skrchnavy** [comment]
L-Catalog is not supported and was completely removed from distribution.
so we shall remove also configuration lines related to that DPU.

**Comment by Jan-Marcek** [comment]
a) the place `/var/www/dump/` where the dumps can be placed remains . If dump.zip is placed to `/var/www/dump/` then it is accessible via http://host/dump/dump.zip. 

b) User can upload files via https://github.com/OpenDataNode/UVPlugin-filesToCKAN as well.
The difference between a) and b): a) doesn't make record to ckan - internalcatalog. b) does.

Solution b) is recommended

L-catalog property was removed from ic configuration
