### ISSUE TITLE
'cat 'in odn-simple.postinst eating 100% CPU and "hanging" upgrade

### ISSUE THREAD

**Issue by hanecak** [OpenDataNode/odn-box#33]
I'm performing upgrade of ODN from 1.0.3 to 1.1.0 and it got "frozen" at:

```
...
DETAIL:  Key (owner_id)=(5) is not present in table "usr_user".
ALTER TABLE
[ ok ] Stopping Tomcat servlet engine: odn-solr.
[ ok ] Starting Tomcat servlet engine: odn-solr.
wait for restart
>> db_up
INFO: Waiting for postgresql to be up... Done
<<
```

`cat` command launched by `odn-simple.postins` is eating 100% and did not stop even after 30 minutes.

Presumably, this seems to be the offending line:

```
cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w ${1:-32} | head -n 1
```

(https://github.com/OpenDataNode/odn-box/blob/master/debian/odn-simple.postinst#L210)

I guess `cat` tries to "read all" even though the intention is to get only something like first 32 or so bytes.

So maybe a better way would be:

```
head -c 256 /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w ${1:-32} | head -n 1
```

**Comment by hanecak** [comment]
I've killed the `cat`. Observed output:

```
...
>> db_up
INFO: Waiting for postgresql to be up... Done
<<

Terminated
fold: write error: Broken pipe
>> install_theme
...
dpkg: error processing odn-simple (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 odn-simple

Current status: 0 updates [-22].
```

Public catalog is now reporting ODN 1.1 .

Login to internal catalog does not work (ERROR 500 from http://xxx/internalcatalog/). That might be unrelated to the issue at hand.

**Comment by skrchnavy** [comment]
there are lot of ways how to generate the key (http://www.howtogeek.com/howto/30184/10-ways-to-generate-a-random-password-from-the-command-line/)
32 chars string is expected so md5sum is also nice to use ( `head -c16 /dev/urandom | md5sum`)
