### ISSUE TITLE
default ckan.max_resource_size too small

### ISSUE THREAD

**Issue by spinque** [OpenDataNode/odn-box#37]
The default value `ckan.max_resource_size = 10` (10MB) seems inadequately small to me. 
Especially considering that in case of a larger upload to the catalog, the pipeline fails with no clear message about this. The actual error can only be found by inspecting the result of the relativ REST call:

```
Response:{"help":
"https://odn.spinque.com/internalcatalog/api/3/action/help_show?name=internal_api
<https://www.google.com/url?q=https%3A%2F%2Fodn.spinque.com%2Finternalcatalog%2Fapi%2F3%2Faction%2Fhelp_show%3Fname%3Dinternal_api&sa=D&sntz=1&usg=AFQjCNFw1jXVm_4SMq6dSIGCTvr1qaMOxQ>",
"success": false, "error": {"__type": "Validation Error", "upload":
["File upload too large"]}}
```

**Comment by skrchnavy** [comment]
To setup value in odn installation to  `ckan.max_resource_size = 100` (100MB)
